backend:
  name: git-gateway
  branch: master
media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "images"
collections:
  - name: "pizzas" # Used in routes, e.g., /admin/collections/post
    label: "Pizzas" # Used in the UI
    folder: "content/pizzas" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Nummer", name: "number", widget: "string" }
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Beskrivelse", name: "beskrivelse", widget: "text" }
      - label: "Kategori"
        name: "category"
        widget: "select"
        options:
          - { label: "Traditionel pizza", value: "1" }
          - { label: "Special pizza", value: "2" }
          - { label: "Kurdisk pizza", value: "3" }
      - { label: "Billede", name: "image", widget: "image" }

  - name: "pages"
    label: "Sider"
    files:
      - file: "content/_index.md"
        label: "Forside"
        name: "home"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Underoverskrift", name: "blurb", widget: "text" }
